name: piece-buffer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}
  publish:
      runs-on: ubuntu-latest
      needs: release
      if: steps.release.outputs.released == 'true'
      steps:
        - uses: actions/checkout@v3
        # Setup .npmrc file to publish to npm
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        # Need to compile *before* setting the npm registry to wombat, otherwise
        # npm will try to use the publish service for installing, which is verbotten.
        - run: npm run compile
        - run: echo "//wombat-dressing-room.appspot.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        - run: echo "registry=https://wombat-dressing-room.appspot.com/" >> .npmrc
        - run: echo "always-auth=true" >> .npmrc
        - run: cat .npmrc
        - run: npm publish
